GET http://localhost:5000/actors

###

GET http://localhost:5000/actors/2

###

POST http://localhost:5000/actors HTTP/1.1
Content-Type: application/json

{
    "full_name": "James Kirk",
    "birth_year": "1989-01-14",
    "death_year": "2026-02-24",
    "photo": "kirk.jpg",
    "country": "AUS"
}

###

PUT http://localhost:5000/actors HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "full_name": "Tomas Geffroy",
    "birth_year": "1989-01-14",
    "death_year": "2019-07-10",
    "photo": "geffroy.jpg",
    "country": "ITA"
}

###

DELETE http://localhost:5000/actors/2
