GET http://localhost:5000/directors

###

GET http://localhost:5000/directors/2

###

POST http://localhost:5000/directors HTTP/1.1
Content-Type: application/json

{
    "full_name": "Kirk De Micco",
    "birth_year": "1954-08-16",
    "death_year": "1990-05-08",
    "photo": "de_micco.jpg",
    "country": "ESP"
}

###

PUT http://localhost:5000/directors HTTP/1.1
Content-Type: application/json

{
    "id": 2,
    "full_name": "Stevy Rogers",
    "birth_year": "1954-08-16",
    "death_year": "1990-05-08",
    "photo": "rogers.jpg",
    "country": "CAN"
}

###

DELETE http://localhost:5000/directors/2